= Quarkus Workshop Guide Source Code

This is the source code for the https://github.com/RedHatWorkshops/quarkus-workshop[Quarkus Workshop].

This workshop focuses on https://quarkus.io[Quarkus], supersonic, subatomic container-native Java. The workshop uses https://eclipse.org/che[Eclipse Che] to develop Quarkus apps and deploy them to a Kubernetes cluster (based on OpenShift), and covers several other developer topics.





curl http://localhost:8080/health/ready

curl http://localhost:8080/health/live





Quarkus itself is configured via the same mechanism as your application. Quarkus reserves the quarkus. namespace in application.properties for its own configuration.

It is also possible to generate an example application.properties with all known configuration properties, to make it easy to see what Quarkus configuration options are available depending on which extensions you’ve enabled. To do this, open a Terminal and run:

    mvn -q quarkus:generate-config -f quarkus-workshop-m1m2-labs




The syntax for this is %{profile}.config.key=value. For example if I have the following: (do not copy this code!):

quarkus.http.port=9090
%dev.quarkus.http.port=8181




list all extenions 

    mvn -q quarkus:list-extensions -f quarkus-workshop-m1m2-labs





Seciton 2

mvn -q quarkus:add-extension -Dextensions="hibernate-orm-panache, jdbc-h2, jdbc-postgresql, resteasy-jsonb" -f $CHE_PROJECTS_ROOT/quarkus-workshop-m1m2-labs
mvn -q quarkus:add-extension -Dextensions="smallrye-openapi" -f $CHE_PROJECTS_ROOT/quarkus-workshop-m1m2-labs


OpenAPI 

yaml 

    curl http://localhost:8080/openapi

if you want json instead of yaml 

    curl -H "Accept: application/json" http://localhost:8080/openapi



Swagger 

http://localhost:8080/swagger-ui


# Events 


Quarkus allows different beans to interact using asynchronous messages, enforcing loose-coupling. The messages are sent to virtual addresses. It offers 3 types of delivery mechanism:

    Point-to-Point - send the message, one consumer receives it. If several consumers listen to the address, a round robin is applied;

    Publish/Subscribe - publish a message, all the consumers listening to the address are receiving the message;

    Request/Reply - send the message and expect a response. The receiver can respond to the message in an asynchronous-fashion

All these delivery mechanism are non-blocking, and provide one of the fundamental building blocks of reactive systems which promise better performance, reduced developer burden, better isolation between services, and improved recovery from failure.
	

The asynchronous message passing feature in Quarkus allows replying to messages — which is not supported by Reactive Messaging. However, it is limited to single-event behavior (no stream) and to local messages.


Eclipse Vert.x is a toolkit for building reactive applications. It is designed to be lightweight and embeddable. Vert.x defines a reactive execution model and provides a large ecosystem. Quarkus integrates Vert.x to implement different reactive features, such as asynchronous message passing (the subject of this exercise), and non-blocking HTTP client. Basically, Quarkus uses Vert.x as its reactive engine. While lots of reactive features from Quarkus don’t show Vert.x, it’s used underneath. But you can also access the managed Vert.x instance and benefit from the Vert.x ecosystem.


mvn -q quarkus:add-extension -Dextensions="vertx" -f quarkus-workshop-m1m2-labs




Quarkus provides 3 Vert.x APIs:

    bare - for advanced usage or if you have existing Vert.x code you want to reuse in your Quarkus application

    Axle - works well with Quarkus and MicroProfile APIs (CompletionStage for single results and Publisher for streams)

    Rx Java 2 - when you need support for a wide range of data transformation operators on your streams

We’re using the Axle variant here, which provides good support for async operations in HTTP resources.




To better understand, let’s detail how the HTTP request/response has been handled:

    The request is received by the addPerson method

    a message containing the desired name is sent to the event bus

    Another bean receives this message and computes the response

    This response is sent back using the reply mechanism

    Once the reply is received by the sender, the content is written to the HTTP response



